package DAO;
// Generated 24 janv. 2012 14:13:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set users = new HashSet(0);
     private Set files = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set users_1 = new HashSet(0);

    public Group() {
    }

	
    public Group(String name) {
        this.name = name;
    }
    public Group(String name, Set users, Set files, Set messages, Set users_1) {
       this.name = name;
       this.users = users;
       this.files = files;
       this.messages = messages;
       this.users_1 = users_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getUsers_1() {
        return this.users_1;
    }
    
    public void setUsers_1(Set users_1) {
        this.users_1 = users_1;
    }




}


