package DAO;
// Generated 16 janv. 2012 17:03:25 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Group group;
     private String title;
     private String content;
     private Date createdAt;
     private Set comments = new HashSet(0);

    public Message() {
    }

	
    public Message(User user, Group group, String content, Date createdAt) {
        this.user = user;
        this.group = group;
        this.content = content;
        this.createdAt = createdAt;
    }
    public Message(User user, Group group, String title, String content, Date createdAt, Set comments) {
       this.user = user;
       this.group = group;
       this.title = title;
       this.content = content;
       this.createdAt = createdAt;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


