package DAO;
// Generated 13 janv. 2012 15:13:13 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Group group;
     private String title;
     private String content;
     private Date createdAt;
     private Date updatedAt;
     private Set comments = new HashSet(0);

    public Messages() {
    }

	
    public Messages(User user, Group group, String content, Date createdAt, Date updatedAt) {
        this.user = user;
        this.group = group;
        this.content = content;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Messages(User user, Group group, String title, String content, Date createdAt, Date updatedAt, Set comments) {
       this.user = user;
       this.group = group;
       this.title = title;
       this.content = content;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


